# Generated by Django 4.2.7 on 2025-07-01 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                            ("published", "Published"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "moderator"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "equipment",
                    models.TextField(
                        blank=True, help_text="List of available equipment"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum number of researchers"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                            ("published", "Published"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="organization.department",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "role__in": ["admin", "moderator", "researcher"]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_labs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratory",
                "verbose_name_plural": "Laboratories",
                "ordering": ["department__name", "name"],
                "unique_together": {("name", "department")},
            },
        ),
        migrations.CreateModel(
            name="ResearcherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Position/role in the lab (e.g., PhD Student, Postdoc, Research Assistant)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                            ("published", "Published"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the assignment"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "moderator"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researcher_assignments",
                        to="organization.department",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researcher_assignments",
                        to="organization.lab",
                    ),
                ),
                (
                    "researcher",
                    models.ForeignKey(
                        limit_choices_to={"role": "researcher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Researcher Assignment",
                "verbose_name_plural": "Researcher Assignments",
                "ordering": ["-start_date"],
                "unique_together": {("researcher", "lab", "start_date")},
            },
        ),
    ]
