# Generated by Django 4.2.7 on 2025-07-11 14:32

import django.core.validators
from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="Scientific Research Organization",
                        help_text="Organization name",
                        max_length=200,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        default="Scientific Research Organization",
                        help_text="Organization name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        default="Scientific Research Organization",
                        help_text="Organization name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "vision",
                    models.TextField(
                        blank=True, help_text="Organization vision statement"
                    ),
                ),
                (
                    "vision_ar",
                    models.TextField(
                        blank=True, help_text="Organization vision statement", null=True
                    ),
                ),
                (
                    "vision_en",
                    models.TextField(
                        blank=True, help_text="Organization vision statement", null=True
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True, help_text="Organization mission statement"
                    ),
                ),
                (
                    "mission_ar",
                    models.TextField(
                        blank=True,
                        help_text="Organization mission statement",
                        null=True,
                    ),
                ),
                (
                    "mission_en",
                    models.TextField(
                        blank=True,
                        help_text="Organization mission statement",
                        null=True,
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, help_text="About the organization"),
                ),
                (
                    "about_ar",
                    models.TextField(
                        blank=True, help_text="About the organization", null=True
                    ),
                ),
                (
                    "about_en",
                    models.TextField(
                        blank=True, help_text="About the organization", null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Main contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Main contact phone", max_length=20
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Organization address"),
                ),
                (
                    "address_ar",
                    models.TextField(
                        blank=True, help_text="Organization address", null=True
                    ),
                ),
                (
                    "address_en",
                    models.TextField(
                        blank=True, help_text="Organization address", null=True
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Official website URL"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, help_text="Facebook page URL"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, help_text="Twitter profile URL"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="LinkedIn page URL"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, help_text="Instagram profile URL"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo (JPG, PNG, SVG)",
                        upload_to=organization.models.upload_to_organization,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Organization banner image (JPG, PNG)",
                        upload_to=organization.models.upload_to_organization,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "enable_registration",
                    models.BooleanField(
                        default=True, help_text="Allow new user registration"
                    ),
                ),
                (
                    "require_approval",
                    models.BooleanField(
                        default=True, help_text="Require admin approval for new users"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, help_text="Enable maintenance mode"
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True, help_text="Message to display during maintenance"
                    ),
                ),
                (
                    "maintenance_message_ar",
                    models.TextField(
                        blank=True,
                        help_text="Message to display during maintenance",
                        null=True,
                    ),
                ),
                (
                    "maintenance_message_en",
                    models.TextField(
                        blank=True,
                        help_text="Message to display during maintenance",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Settings",
                "verbose_name_plural": "Organization Settings",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="location_ar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="location_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="name_ar",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="department",
            name="name_en",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="equipment_ar",
            field=models.TextField(
                blank=True, help_text="List of available equipment", null=True
            ),
        ),
        migrations.AddField(
            model_name="lab",
            name="equipment_en",
            field=models.TextField(
                blank=True, help_text="List of available equipment", null=True
            ),
        ),
        migrations.AddField(
            model_name="lab",
            name="location_ar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="location_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="name_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
