# Generated by Django 4.2.7 on 2025-07-12 14:44

import django.core.validators
from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0002_organizationsettings_department_description_ar_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="mission_image",
            field=models.ImageField(
                blank=True,
                help_text="Mission statement image (JPG, PNG)",
                upload_to=organization.models.upload_to_organization,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="vision_image",
            field=models.ImageField(
                blank=True,
                help_text="Vision statement image (JPG, PNG)",
                upload_to=organization.models.upload_to_organization,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
