# Generated by Django 4.2.7 on 2025-07-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationsettings_mission_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location_ar',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='equipment_ar',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='equipment_en',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='location_ar',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='about_ar',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='maintenance_message_ar',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='maintenance_message_en',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mission_ar',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mission_en',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='vision_ar',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='vision_en',
        ),
    ]
