# Generated by Django 4.2.7 on 2025-09-01 17:12

import django.core.validators
from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_department_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='About section image (JPG, PNG)', upload_to=organization.models.upload_to_organization, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
