# Generated by Django 4.2.7 on 2025-07-05 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicianassignment",
            name="current_requests",
        ),
        migrations.RemoveField(
            model_name="testservice",
            name="current_requests",
        ),
    ]
