# Generated by Django 5.2.4 on 2025-08-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_technicianassignment_current_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testservice',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for service listings', max_length=100000),
        ),
    ]
