# Generated by Django 4.2.7 on 2025-08-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_testservice_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Service image', upload_to='services/images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for the service')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='technicianassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='technicianassignment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='technicianassignment',
            name='technician',
        ),
        migrations.RemoveIndex(
            model_name='testservice',
            name='services_te_is_feat_e8296f_idx',
        ),
        migrations.RemoveIndex(
            model_name='testservice',
            name='services_te_departm_080a90_idx',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='equipment_used',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='max_concurrent_requests',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='pricing_structure',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='required_documents',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='safety_requirements',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='sample_requirements',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='service_brochure',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='testservice',
            name='technicians',
        ),
        migrations.AlterField(
            model_name='testservice',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for this service', max_length=254),
        ),
        migrations.AlterField(
            model_name='testservice',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone for this service', max_length=20),
        ),
        migrations.AlterField(
            model_name='testservice',
            name='description',
            field=models.TextField(help_text='Full service description'),
        ),
        migrations.AlterField(
            model_name='testservice',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main service image', null=True, upload_to='services/images/'),
        ),
        migrations.AlterField(
            model_name='testservice',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured service'),
        ),
        migrations.AlterField(
            model_name='testservice',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether this service is free'),
        ),
        migrations.AlterField(
            model_name='testservice',
            name='name',
            field=models.CharField(help_text='Service name', max_length=200),
        ),
        migrations.AlterField(
            model_name='testservice',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=200),
        ),
        migrations.AddIndex(
            model_name='testservice',
            index=models.Index(fields=['is_featured'], name='services_te_is_feat_8a5c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='testservice',
            index=models.Index(fields=['service_code'], name='services_te_service_40ddce_idx'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.DeleteModel(
            name='TechnicianAssignment',
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.testservice'),
        ),
    ]
