# Generated by Django 4.2.7 on 2025-07-25 19:24

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="academic_degree",
            field=models.CharField(
                blank=True, help_text="Highest academic degree", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="position",
            field=models.CharField(
                blank=True, help_text="Current position/title", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload profile image (JPG, PNG only)",
                null=True,
                upload_to=core.models.upload_to_user_directory,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="specialization",
            field=models.CharField(
                blank=True, help_text="Area of specialization", max_length=200
            ),
        ),
    ]
