# Generated by Django 4.2.7 on 2025-07-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userprofile_academic_degree_userprofile_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, help_text="Phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for admin use", max_length=1000
            ),
        ),
    ]
