# Generated by Django 4.2.7 on 2025-07-26 13:48

import django.core.validators
from django.db import migrations, models
import research.models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-priority", "-publication_date", "-created_at"],
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
        ),
        migrations.RemoveIndex(
            model_name="publication",
            name="research_pu_status_d46478_idx",
        ),
        migrations.AddField(
            model_name="publication",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Feature this publication"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Priority for ordering (0-10)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="publicationmetrics",
            name="quality_score",
            field=models.FloatField(
                default=0.0,
                help_text="Quality score (0-10)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="abstract",
            field=models.TextField(
                blank=True, help_text="Publication abstract", max_length=2000
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="citation_count",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="conference_name",
            field=models.CharField(
                blank=True, help_text="Conference name", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="Upload publication document (PDF, DOC, DOCX only, max 10MB)",
                upload_to=research.models.upload_to_publications,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="Digital Object Identifier (must start with 10.)",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Make publication visible to public",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="issue",
            field=models.CharField(blank=True, help_text="Issue number", max_length=50),
        ),
        migrations.AlterField(
            model_name="publication",
            name="journal_name",
            field=models.CharField(
                blank=True, help_text="Journal name", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pages",
            field=models.CharField(
                blank=True, help_text="Page range (e.g., 123-145)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publication_date",
            field=models.DateField(
                blank=True, db_index=True, help_text="Date of publication", null=True
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publication_type",
            field=models.CharField(
                choices=[
                    ("journal_article", "Journal Article"),
                    ("conference_paper", "Conference Paper"),
                    ("book_chapter", "Book Chapter"),
                    ("book", "Book"),
                    ("thesis", "Thesis"),
                    ("report", "Report"),
                    ("preprint", "Preprint"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="journal_article",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publisher",
            field=models.CharField(
                blank=True, help_text="Publisher name", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="research_area",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Research area/field",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("draft", "Draft"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(help_text="Publication title", max_length=500),
        ),
        migrations.AlterField(
            model_name="publication",
            name="volume",
            field=models.CharField(
                blank=True, help_text="Volume number", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="publicationauthor",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Order of author in publication (1 = first author)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publicationauthor",
            name="role",
            field=models.CharField(
                blank=True, help_text="Author's role in the research", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="altmetric_score",
            field=models.FloatField(
                blank=True, help_text="Altmetric attention score", null=True
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="citation_count",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="download_count",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="facebook_shares",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="linkedin_shares",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="mendeley_readers",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="researchgate_reads",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="twitter_mentions",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="publicationmetrics",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["status", "is_public"], name="research_pu_status_82b4f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["research_area"], name="research_pu_researc_5d92a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["is_featured", "priority"],
                name="research_pu_is_feat_390944_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["corresponding_author"], name="research_pu_corresp_ec27c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["submitted_by"], name="research_pu_submitt_928089_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationauthor",
            index=models.Index(
                fields=["is_corresponding"], name="research_pu_is_corr_287780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationauthor",
            index=models.Index(
                fields=["is_first_author", "is_last_author"],
                name="research_pu_is_firs_191160_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicationmetrics",
            index=models.Index(
                fields=["view_count"], name="research_pu_view_co_caf292_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationmetrics",
            index=models.Index(
                fields=["download_count"], name="research_pu_downloa_e9bcf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationmetrics",
            index=models.Index(
                fields=["citation_count"], name="research_pu_citatio_837346_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationmetrics",
            index=models.Index(
                fields=["quality_score"], name="research_pu_quality_ce31be_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                check=models.Q(("priority__gte", 0), ("priority__lte", 10)),
                name="valid_priority_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationauthor",
            constraint=models.CheckConstraint(
                check=models.Q(("order__gte", 1), ("order__lte", 100)),
                name="valid_author_order",
            ),
        ),
    ]
