# Generated by Django 4.2.7 on 2025-07-28 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0002_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationmetrics',
            options={'ordering': ['-citation_count', '-view_count'], 'verbose_name': 'Publication Metrics', 'verbose_name_plural': 'Publication Metrics'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('published', 'Published')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, help_text='Publication title', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicationauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_authorships', to=settings.AUTH_USER_MODEL),
        ),
    ]
