# Generated by Django 4.2.7 on 2025-08-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_publicationmetrics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(help_text='Publication abstract', max_length=2000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_name',
            field=models.CharField(help_text='Journal name', max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('journal_article', 'Journal Article'), ('conference_paper', 'Conference Paper'), ('book_chapter', 'Book Chapter'), ('book', 'Book'), ('thesis', 'Thesis'), ('report', 'Report'), ('preprint', 'Preprint'), ('other', 'Other')], db_index=True, default='journal_article', help_text='Type of publication', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(help_text='Publication title', max_length=500, null=True),
        ),
    ]
