# Generated by Django 4.2.7 on 2025-08-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_publication_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='journal_name',
            field=models.CharField(blank=True, help_text='Journal name', max_length=300),
        ),
    ]
