# Generated by Django 4.2.7 on 2025-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_publication_journal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier (must start with 10.)', max_length=200, null=True),
        ),
    ]
