# Generated by Django 4.2.7 on 2025-07-02 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_comment_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
        migrations.DeleteModel(
            name="PostLike",
        ),
    ]
