# Generated by Django 4.2.7 on 2025-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_announcementimage_announcementattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="content_ar",
            field=models.TextField(help_text="Main announcement content", null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="content_en",
            field=models.TextField(help_text="Main announcement content", null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="summary_ar",
            field=models.CharField(
                blank=True,
                help_text="Brief summary for list views (auto-generated if empty)",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="summary_en",
            field=models.CharField(
                blank=True,
                help_text="Brief summary for list views (auto-generated if empty)",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content_ar",
            field=models.TextField(help_text="Main post content", null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=models.TextField(help_text="Main post content", null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="event_location_ar",
            field=models.CharField(
                blank=True,
                help_text="Location for events (optional)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="event_location_en",
            field=models.CharField(
                blank=True,
                help_text="Location for events (optional)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt_ar",
            field=models.CharField(
                blank=True,
                help_text="Brief excerpt for list views (auto-generated if empty)",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt_en",
            field=models.CharField(
                blank=True,
                help_text="Brief excerpt for list views (auto-generated if empty)",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
