# Generated by Django 4.2.7 on 2025-07-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_announcement_content_ar_announcement_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='summary_ar',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_location_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_location_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
    ]
