# Generated by Django 5.2.3 on 2025-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_announcement_content_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('published', 'Published')], default='pending', help_text='Post status: pending (awaiting review) or published (live)', max_length=20),
        ),
    ]
