# Generated by Django 5.2.4 on 2025-08-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_post_is_deleted'),
        ('content', '0007_simplify_post_status'),
    ]

    operations = [
    ]
