# Generated by Django 4.2.7 on 2025-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summertrainingapplication",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Upload your CV/Resume (optional)",
                null=True,
                upload_to="training/applications/cvs/",
            ),
        ),
    ]
