# Generated by Django 5.2.3 on 2025-07-30 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for guest enrollment', max_length=254),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='enrollment_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique token for guest enrollment access', unique=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name for guest enrollment', max_length=100),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title for guest enrollment', max_length=100),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name for guest enrollment', max_length=100),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization/Company for guest enrollment', max_length=200),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for guest enrollment', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Registered user (null for guest enrollments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['enrollment_token'], name='training_co_enrollm_29b496_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('course', 'student'), name='unique_course_student'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True)), fields=('course', 'email'), name='unique_course_guest_email'),
        ),
    ]
