# Generated by Django 5.2.3 on 2025-07-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_courseenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], help_text='Education level for guest enrollment', max_length=50),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Experience level for guest enrollment', max_length=50),
        ),
    ]
