# Generated by Django 5.2.3 on 2025-07-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_courseenrollment_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='experience_level',
        ),
    ]
