# Generated by Django 5.2.3 on 2025-07-31 21:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_courseenrollment_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='payment_reference',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('mobile_payment', 'Mobile Payment'), ('check', 'Check'), ('other', 'Other')], help_text='Method used for payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid or to be paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current payment status', max_length=20),
        ),
    ]
