# Generated by Django 4.2.7 on 2025-08-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_summertrainingapplication_cv_file'),
        ('training', '0005_add_payment_method'),
    ]

    operations = [
    ]
