# Generated by Django 5.2.4 on 2025-08-09 19:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_department_description_ar_and_more'),
        ('training', '0006_merge_20250806_1340'),
    ]

    operations = [
        # Remove only the fields that actually exist in your database
        # Based on your schema, none of these fields exist, so we'll remove all RemoveField operations
        
        # Add new fields
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Course cost/fee',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(
                default='',
                help_text='Name of the course',
                max_length=200
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='training_hours',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Total training hours for the course'
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(
                choices=[
                    ('course', 'Course'),
                    ('summer_training', 'Summer Training'),
                    ('public_service', 'Public Service'),
                    ('workshop', 'Workshop'),
                    ('seminar', 'Seminar')
                ],
                default='course',
                help_text='Type of training/course',
                max_length=20
            ),
        ),
        
        # Alter existing fields
        migrations.AlterField(
            model_name='course',
            name='current_enrollment',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Current number of enrolled participants'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(
                blank=True,
                help_text='Department offering this course (optional)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='courses',
                to='organization.department'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(
                help_text='Detailed course description'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(
                help_text='Course end date'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(
                blank=True,
                help_text='Course promotional image',
                null=True,
                upload_to='training/courses/'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(
                default='',
                help_text='Name of the course instructor (can be external)',
                max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(
                default=False,
                help_text='Whether to feature this course'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(
                default=True,
                help_text='Whether this course is publicly visible'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_participants',
            field=models.PositiveIntegerField(
                default=30,
                help_text='Maximum number of participants'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_deadline',
            field=models.DateField(
                help_text='Last date for registration'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(
                help_text='Course start date'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('active', 'Active'),
                    ('inactive', 'Inactive'),
                    ('draft', 'Draft'),
                    ('published', 'Published')
                ],
                default='draft',
                help_text='Course status',
                max_length=20
            ),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='course',
            index=models.Index(
                fields=['type'],
                name='training_co_type_846607_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(
                fields=['registration_deadline'],
                name='training_co_registr_5c1dc8_idx'
            ),
        ),
    ]