# Generated by Django 4.2.7 on 2025-08-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_backup'),
        ('training', '0007_remove_course_training_co_trainin_961961_idx_and_more'),
    ]

    operations = [
    ]
